### ISSUE TITLE
Use `ActorQueue.main` instead of `MainActorQueue.shared` for main actor operations

### ISSUE THREAD

**Issue by ahmdmhasn** [dfed/swift-async-queue#23]
**Objectives**
Simplify the API to align with the Foundation DispatchQueue APIs.

**Exclusions**
Considering the compile-time nature of `@MainActor`, achieving this might pose challenges.

**Explorations**
What alternative solutions were explored, if any, and why were they not selected?

**Blueprint**
This proposal intends to enable the reuse of `ActorQueue` across various `actor`s, streamlining the API for enhanced usability. Consequently, the substitution of `MainActorQueue.shared` with `ActorQueue.main` is proposed.

**Comment by dfed** [comment]
I like this a lot! It would be pretty straight forward to have `ActorQueue` vend a `public static var main: MainActorQueue` type. Unlike `DispatchQueue.main`, the type returned by this property would be of another type (`ActorQueue` vs `MainActorQueue`), but I think that's fine?

We need a separate type here because we need our `enqueue` methods to take `@MainActor`-bound tasks.

**Comment by dfed** [comment]
Tried playing with this. The main issue is that `ActorQueue.main` does _not_ compile, since `ActorQueue` has a generic type `ActorType: Actor`. As much as I love this idea for a convenience method, I'm coming up short on what we can do to actually achieve the goal without complicating the system. I'll leave this open a bit longer in the hopes that someone will come up with an idea here. If we can't come up with something, I'll close this in a week or so.

**Comment by dfed** [comment]
Closing since we haven't come up with something here. I still like this idea though, and am open to suggestions! Happy to re-open if we can come up with an approach that'll work.

**Comment by dfed** [comment]
We made this better in `0.7.0`!
